substitutions:
  _VERSION: v1.0.8
steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/us.gcr.io/sample-ci-cd:${_VERSION}', '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/${PROJECT_ID}/us.gcr.io/sample-ci-cd:${_VERSION}']

# Deploy create release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'releases'
  - 'create'
  - 'test-release-${DATE}-${TIME}'
  - '--project'
  - 'sandbox-383520'
  - '--region'
  - 'us-east1'
  - '--delivery-pipeline'
  - 'ci-cd-tutorial-sample-app'
  - '--images'
  - 'sample-ci-cd=us-docker.pkg.dev/${PROJECT_ID}/us.gcr.io/sample-ci-cd:${_VERSION}'
#  - '--port'
#  - '8000'
images:
- 'us-docker.pkg.dev/${PROJECT_ID}/us.gcr.io/sample-ci-cd:${_VERSION}'

