apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-qs-prod
spec:
  template:
    spec:
      containers:
      - image: sample-ci-cd
        ports:
        - containerPort: 8000